apiVersion: v1
kind: Service
metadata:
  name: {{ include "mnemon-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mnemon-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    app.kubernetes.io/name: {{ include "mnemon-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
