#!/usr/bin/env bash
# Mnemon goal loop runtime config.
# Host projectors copy this file next to GUIDE.md and loop.json.

MNEMON_GOAL_LOOP_ENV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MNEMON_GOAL_LOOP_HARNESS_DIR="$(cd "${MNEMON_GOAL_LOOP_ENV_DIR}/.." && pwd)"

export MNEMON_GOAL_LOOP_ENV="${MNEMON_GOAL_LOOP_ENV:-${MNEMON_GOAL_LOOP_ENV_DIR}/env.sh}"
export MNEMON_GOAL_LOOP_DIR="${MNEMON_GOAL_LOOP_DIR:-${MNEMON_GOAL_LOOP_ENV_DIR}}"
export MNEMON_GOAL_LOOP_ROOT="${MNEMON_GOAL_LOOP_ROOT:-$(cd "${MNEMON_GOAL_LOOP_HARNESS_DIR}/../.." && pwd)}"
export MNEMON_GOAL_LOOP_GOALS_DIR="${MNEMON_GOAL_LOOP_GOALS_DIR:-${MNEMON_GOAL_LOOP_HARNESS_DIR}/goals}"
export MNEMON_GOAL_LOOP_STATUS_DIR="${MNEMON_GOAL_LOOP_STATUS_DIR:-${MNEMON_GOAL_LOOP_HARNESS_DIR}/status/goals}"
